config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'gunplas#index'

  get '/gunplas/collection', to: 'gunplas#show_collection'

  delete '/gunplas/:gunpla_id/collection', to: 'gunplas#delete_gunpla_from_collection'

  resources :gunplas, only: [:index, :show] do
    post 'collection', to: 'gunplas#add_collection'
    resources :reviews, except: [:index]
  end

end

app/models/gunpla.rb
class Gunpla < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :users
  has_many_attached :images, dependent: :destroy

  validates *%i[kit_name gundam_name grade scale gundam_series],
    presence: true

  scope :gunpla_collection, -> (user) {where("user_id = ?", user)}

  def self.sort_all_by_review
    Gunpla.all.sort {|zap, zoo|
      zap.reviews.average(:rating) <=> zoo.reviews.average(:rating)
    }.reverse()
  end

  def reviews_avg
    self.reviews.average(:rating).round(1).to_f()
  end

end

app/controllers/gunplas_controller.rb
class GunplasController < ApplicationController

  def index
    @top_gunpla = get_top_reviews()
    render :index
  end

  def show
    @gunpla = Gunpla.find(params[:id])
    @gunplas_related = get_eight_random()
    @reviews = Review.gunpla_reviews(@gunpla.id)
    @liked = render_liked()
    render :show
  end

  def create
    @gunpla = Gunpla.new(gunpla_params)
    if @gunpla.save
      flash[:notice] = 'Gunpla successfully created'
      redirect_to gunplas_path
    else
      render :new
    end
  end

  def new
    @gunpla = Gunpla.new
    render :new
  end

  def edit
    @gunpla = Gunpla.find(params[:id])
    render :edit
  end

  def update
    @gunpla = Gunpla.find(params[:id])
    if @gunpla.update(gunpla_params)
      flash[:notice] = 'Gunpla successfully updated'
      redirect_to gunplas_path
    else
      render :edit
    end
  end

  def destroy
    @gunpla = Gunpla.find(params[:id]).destroy
    flash[:alert] = 'Gunpla has been successfully deleted'
    redirect_to gunplas_path
  end

  def add_collection
    @user = User.find(current_user.id)
    gunpla = Gunpla.find(params['gunpla_id'])
    if gunpla.users.include?(@user)
    else
      gunpla.users << @user
      redirect_to gunplas_collection_path
    end
  end

  def show_collection
    @user = nil
    if current_user&.id
      @user = User.find(current_user.id)
    end
    @gunplas = Gunpla.all
    render :collection
  end

  def delete_gunpla_from_collection
    @user = User.find(current_user.id)
    gunpla = Gunpla.find(params['gunpla_id'])
    if gunpla.users.include?(@user)
      gunpla.users.destroy(@user)
      redirect_to gunplas_collection_path
    end
  end

  private

  # def collection_params
  #   params.require(:gunpla).permit(:gunpla_id)
  # end

  def render_liked
    @user = current_user && User.find(current_user.id)
    @gunpla.users.include?(@user) ? '♥️' : '♡'
  end

  def gunpla_params
    params.require(:gunpla).permit(:kit_name, :gundam_name, :gundam_series, :grade, :scale)
  end


  def get_top_reviews
    Gunpla.sort_all_by_review.take(12)
  end

  def get_twelve_random
    Gunpla.all.sample(12)
  end

  def get_eight_random
    Gunpla.all.sample(8)
  end
end




# test_array_of_arrays = []
# 1000.times {
#   array = []
#   1000.times {
#     array << rand(1..100)
#   }
#   test_array_of_arrays << array
# }

# Gunpla.all

# @gunpla.sort! {|zap, zoo|
#   zap.reviews.average(:rating) <=> zoo.reviews.average(:rating)
# }

# zap.each do |za|
#   p za.reduce(:+)
# end

app/views/gunplas/collection.html.erb
<div id="collections-page">
  <div id="collections-wrapper">
    <% if @user != nil && @user&.gunplas.any? %>
      <% @user.gunplas.each do |gunpla| %>
        <div class="box">
          <div class="kit-image center-content">
            <div id='gunpla_delete'>
              <%= form_with url: "/gunplas/#{gunpla.id}/collection", method: "delete" do |form| %>
                <%= form.submit '🗑️' %>
              <% end %>
            </div>
            <a href="<%=  gunpla_path(gunpla)  %>">
              <%= image_tag(gunpla.images.second) %>
            </a>
          </div>
          <div class="kit-info center-content">
            <div><span>Kit Name:</span> <%= gunpla.kit_name %></div>
            <div><span>Gundam Name:</span> <%= gunpla.gundam_name %></div>
            <div><span>Grade:</span> <%= gunpla.grade %></div>
            <div><span>Scale:</span> <%= gunpla.scale %></div>
            <div><span>Gundam Series:</span> <%= gunpla.gundam_series %></div>
          </div>
        </div>
        <% end %>
    <% else %>
      <p>You have no Gunplas in your collection</p>
    <% end %>
  </div>
</div>

app/views/gunplas/index.html.erb
    <div class="home">
      <div id="home-title">White Base Hanger Collections</div>
      <div class="top-grid">
        <% (1..5).each do |box_number| %>
          <% gunpla =  @top_gunpla[box_number - 1]%>
          <div class="box-<%= box_number %>">
            <a href="<%=  gunpla_path(gunpla)  %>">
              <div class="kit_name"><%= gunpla.kit_name %></div>
              <%= image_tag(gunpla.images.first) %>
              <di class="avg-review"v>⭐<%= gunpla.reviews_avg() %></di>
            </a>
          </div>
        <% end %>
      </div>
      <div class="mid-grid">
        <% (1..7).each do |box_number| %>
          <% gunpla =  @top_gunpla[(box_number - 1) + 5]%>
          <div class="box-<%= box_number %>">
          <a href="<%=  gunpla_path(gunpla) %>">
            <div class="kit_name"><%= gunpla.kit_name %></div>
            <%= image_tag(gunpla.images.first) %>
            <di class="avg-review"v>⭐<%= gunpla.reviews_avg() %></di>
          </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/gunplas/show.html.erb
<div class="figures">
  <div class="top-grid">
    <div class='box-1'>
      <div id="caro-container">
        <% @gunpla.images.each do |image| %>
          <div id="caro-i" class='caro-image'>
            <%= image_tag(image) %>
          </div>
        <% end %>
      </div>
      <div id='favorites'>
        <%= form_with url: "/gunplas/#{@gunpla.id}/collection", method: :post do |form| %>
          <%= form.submit "#{@liked}" %>
        <% end %>
      </div>
    </div>
    <div class='box-2'>
      <div id="kit-info">
        <div><span>Kit Name:</span> <%= @gunpla.kit_name %></div>
        <div><span>Gundam Name:</span> <%= @gunpla.gundam_name %></div>
        <div><span>Grade:</span> <%= @gunpla.grade %></div>
        <div><span>Scale:</span> <%= @gunpla.scale %></div>
        <div><span>Gundam Series:</span> <%= @gunpla.gundam_series %></div>
      </div>
      <div class='kit-buttons'>
        <button class='button-default review-button'>
          <a href="<%= new_gunpla_review_path(@gunpla) %>">Add a Review</a>
        </button>
      </div>
    </div>
  </div>
  <div class="bottom-grid">
    <% @gunplas_related.each_with_index do |gunpla, index| %>
      <% box_number = index + 1 %>
      <div class="box-<%= box_number %>">
        <a href="<%=  gunpla_path(gunpla)  %>">
          <%= image_tag(gunpla.images.first) %>
          <div class="kit_name"><%= gunpla.kit_name %></div>
        </a>
      </div>
    <% end %>
  </div>
  <div class='reviews'>
    <% @reviews.reverse_each do |review| %>
      <% user = User.find(review.user_id) %>
      <div class="review">
        <div class="review-info-container">
          <div class="review-info">
            <div class="avatar center-content"><%= image_tag(user.avatar) %></div>
            <div class="author-username"><%= user.username %></div>
            <div class="author-signed-up"><span>Joined <%= user.created_in_english %> Ago</span></div>
            <div class="how-many-posts">
              <%= user.how_many_posts %> Posts
            </div>
            <div class="author-bio">
              <div><%= user.bio %></div>
              <div class="joined">Joined <%= user.created_in_english %> Ago</div>
            </div>
          </div>
        </div>
        <div class="review-body">
            <div><span>Title:</span> <%= review.title %></div>
            <div>
              <span>Rating: </span>
              <% review.rating.to_i.times do %>
                ⭐
              <% end %>
            </div>
            <div id="content_body"><%= sanitize review.content_body %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>